# Generated by Django 3.1.1 on 2020-09-10 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChapInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('content', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='MangaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MangaInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=200)),
                ('current_chap', models.IntegerField(default=1)),
                ('avatar', models.ImageField(null=True, upload_to='')),
                ('time_up', models.DateTimeField(auto_now_add=True)),
                ('manga_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.mangatype')),
            ],
        ),
        migrations.CreateModel(
            name='MangaContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.chapinfo')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.mangainfo')),
            ],
        ),
    ]
