# Generated by Django 3.1.1 on 2020-09-10 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_delete_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangainfo',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
