# Generated by Django 3.1.1 on 2020-09-10 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200910_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangainfo',
            name='manga_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.mangatype'),
        ),
    ]
