# Generated by Django 3.1.1 on 2020-09-11 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200910_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapinfo',
            name='chap',
            field=models.IntegerField(default=1),
        ),
    ]
