# Generated by Django 3.1.1 on 2020-09-12 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_chapinfo_chap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapinfo',
            name='content',
            field=models.ImageField(null=True, upload_to=models.CharField(max_length=200)),
        ),
    ]
