# Generated by Django 3.1.1 on 2020-09-15 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200912_0951'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MangaContent',
        ),
    ]
