# Generated by Django 3.1.1 on 2020-09-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_delete_mangacontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapinfo',
            name='page',
            field=models.IntegerField(default=0),
        ),
    ]
