# Generated by Django 3.1.1 on 2020-09-15 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_chapinfo_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapinfo',
            name='page',
        ),
    ]
